version: "3.9"

services:
  frontend:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx
    networks:
      - hackathon_network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - hackathon_network

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - hackathon_network

volumes:
  db_data:

networks:
  hackathon_network:
