version: "3.9"
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hackathon
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
